sudo: false
dist: xenial
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - python3.5
            - python3.5-dev
            - python-pip
            - python-virtualenv
            # Needed for ARM gcc
            - libbz2-1.0:i386
            - libncurses5:i386

language: cpp

matrix:
    include:
        - compiler: gcc
          env: BUILD_TYPE="tests"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="uwb-beacon"

before_install:
    - git submodule update --init --recursive

install:
    - ci/install.sh

script:
    - ci/build.sh
