dependency-dir: ../lib

depends:
  - chibios-syscalls
  - cmp
  - cmp_mem_access
  - error
  - crc
  - version
  - quadramp

target.arm:
  - src/main.c
  - src/debug.c
  - src/board.c
  - src/bootloader_config.c
  - src/reboot.c
  - src/pwm.c
  - src/servo.c
  - src/uavcan/node.cpp
  - src/uavcan/Reboot_handler.cpp
  - src/uavcan/UAVCANRestart_handler.cpp
  - src/uavcan/ServoPWM_handler.cpp
  - src/uavcan/DigitalOutput_handler.cpp
  - src/uavcan/DigitalInput_pub.cpp
  - ../lib/can-bootloader/config.c

templates:
    app_src.mk.jinja: app_src.mk
